export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_RESIDENT_REQUEST = 'REGISTER_RESIDENT_REQUEST'
export const REGISTER_RESIDENT_SUCCESS = 'REGISTER_RESIDENT_SUCCESS'
export const REGISTER_RESIDENT_FAIL = 'REGISTER_RESIDENT_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'


export const UPDATE_RESIDENT_REQUEST = 'UPDATE_RESIDENT_REQUEST'
export const UPDATE_RESIDENT_SUCCESS = 'UPDATE_RESIDENT_SUCCESS'
export const UPDATE_RESIDENT_RESET = 'UPDATE_RESIDENT_RESET'
export const UPDATE_RESIDENT_FAIL = 'UPDATE_RESIDENT_FAIL'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const FETCH_PAYMENT_HISTORY_REQUEST = 'FETCH_PAYMENT_HISTORY_REQUEST';
export const FETCH_PAYMENT_HISTORY_SUCCESS = 'FETCH_PAYMENT_HISTORY_SUCCESS';
export const FETCH_PAYMENT_HISTORY_FAILURE = 'FETCH_PAYMENT_HISTORY_FAILURE';
export const FETCH_MAINTENANCES_REQUEST = 'FETCH_MAINTENANCES_REQUEST';
export const FETCH_MAINTENANCES_SUCCESS = 'FETCH_MAINTENANCES_SUCCESS';
export const FETCH_MAINTENANCES_FAILURE = 'FETCH_MAINTENANCES_FAILURE';
export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const FETCH_RESERVATIONS_REQUEST = 'FETCH_RESERVATIONS_REQUEST';
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAILURE = 'FETCH_RESERVATIONS_FAILURE';

export const FETCH_ANNOUNCEMENTS_REQUEST = 'FETCH_ANNOUNCEMENTS_REQUEST';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILURE = 'FETCH_ANNOUNCEMENTS_FAILURE';


export const FETCH_LAUNDRYSCHEDULES_REQUEST = 'FETCH_LAUNDRYSCHEDULES_REQUEST';
export const FETCH_LAUNDRYSCHEDULES_SUCCESS = 'FETCH_LAUNDRYSCHEDULES_SUCCESS';
export const FETCH_LAUNDRYSCHEDULES_FAILURE = 'FETCH_LAUNDRYSCHEDULES_FAILURE';